#!/bin/bash

SCRIPT_FOLDER="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_FOLDER="${SCRIPT_FOLDER}/.cache"
CONF_FOLDER="${SCRIPT_FOLDER}/conf"
mkdir -p "${CACHE_FOLDER}"

function echo_error() { echo "$@" 1>&2; }
function exit_error() { echo_error "ERROR - $@"; exit 1; }

# Load $BROKER_VERSION and $DESTINATION_URL from properties file
. ${SCRIPT_FOLDER}/activemq-wrapper.properties
echo "Requiring ActiveMq version: $BROKER_VERSION"

# This is the executable
activemq_home="${CACHE_FOLDER}/${BROKER_VERSION}"
activemq_bin="${activemq_home}/bin/activemq"

# Ensure that the required version is stored in local cache
if [ ! -f "${activemq_bin}" ]; then
    downloaded_artifact="${CACHE_FOLDER}/last_download.tar.gz"
    echo "artifact: ${downloaded_artifact}"

    echo "Version not found in local cache. Downloading from: ${DESTINATION_URL}"
    curl -sS -o "${downloaded_artifact}" -L "${DESTINATION_URL}"
    if [ ! $? -eq 0 ]; then
        exit_error "Failed to download ActiveMq broker"
    fi
    
    # Extract to folder
    tar -xvf "${downloaded_artifact}" -C "${CACHE_FOLDER}" --transform 's/apache-activemq-//'
fi

# Ensure executable
chmod u+x "${activemq_bin}"

# Wrap the activemq broker commands
echo "Execute: ${activemq_bin}"
conf_file="${CONF_FOLDER}/activemq.xml"
EXTRA_OPTS="xbean:file:${conf_file}"
if [ "$1" == "stop" ]; then
   EXTRA_OPTS=""
fi

# Retrieve JMX options. ACTIVEMQ_OPTS is being used by the activemq_bin
JMX_HOST=`cat ${conf_file} | grep -oe "connectorHost=[^ ]*" | cut -d "\"" -f2`
JMX_PORT=`cat ${conf_file} | grep -oe "connectorPort=[^ ]*" | cut -d "\"" -f2`
export ACTIVEMQ_OPTS="-Dactivemq.jmx.url=service:jmx:rmi:///jndi/rmi://${JMX_HOST}:${JMX_PORT}/jmxrmi"

# Run
${activemq_bin} "$@" "${EXTRA_OPTS}"


# Wait for the web console to come up
function wait_until_port_is_open() {
   port=$1
   delay=5
   n=0
   until [ $n -ge 5 ]
   do
     echo  "Is application listening on port $port ? "
     lsof -P -i TCP:${port} > /dev/null
     if [ $? -eq 0 ]; then
        echo "Yes"
        break
     fi
     echo "No. Retrying in $delay seconds."

     n=$[$n+1]
     sleep $delay
   done
}

# Only on start
if [ "$1" == "start" ]; then
   admin_port=`cat ${CONF_FOLDER}/jetty.xml  | grep "\"port\"" | head -n 1 | cut -d "\"" -f 4`
   wait_until_port_is_open ${admin_port}
fi